# Generated by Django 5.2.4 on 2025-07-20 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(choices=[('a', 'Agent'), ('s', 'Supervisor'), ('m', 'Manager')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(choices=[('a', 'Agent'), ('s', 'Supervisor'), ('m', 'Manager')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('call_start_time', models.DateTimeField(auto_now_add=True)),
                ('call_end_time', models.DateTimeField(auto_now=True)),
                ('call_duration', models.DurationField()),
                ('call_status', models.CharField(max_length=10, verbose_name=[('a', 'Answered'), ('m', 'Missed'), ('v', 'Voicemail'), ('b', 'Busy'), ('f', 'Failed')])),
                ('call_purpose', models.CharField(max_length=250)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.agent')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='AiCallAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentiment', models.CharField(max_length=10, verbose_name=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')])),
                ('keywords', models.TextField()),
                ('action_items', models.TextField()),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='crm.call')),
            ],
        ),
    ]
