# Generated by Django 3.2.25 on 2025-07-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
        migrations.AlterField(
            model_name='agent',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_purpose',
            field=models.CharField(max_length=10, verbose_name=[('pi', 'Price Inquiry'), ('wc', 'Warranty Claim')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
