# Generated by Django 3.2.25 on 2025-07-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20250721_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_end_time',
            field=models.DateTimeField(),
        ),
    ]
