# Generated by Django 3.2.25 on 2025-07-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_call_call_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_duration',
            field=models.DurationField(null=True),
        ),
    ]
