# Generated by Django 3.2.25 on 2025-07-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_call_call_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='call_duration',
        ),
    ]
