# Generated by Django 3.2.25 on 2025-07-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_call_call_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_start_time',
            field=models.DateTimeField(),
        ),
    ]
