# Generated by Django 3.2.25 on 2025-07-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_call_call_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Supervisor', 'Supervisor'), ('Manager', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='aicallanalysis',
            name='sentiment',
            field=models.CharField(max_length=10, verbose_name=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')]),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_purpose',
            field=models.CharField(max_length=10, verbose_name=[('Price Inquiry', 'Priceinquiry'), ('Warranty Claim', 'Warrantyclaim')]),
        ),
    ]
