# Generated by Django 3.2.25 on 2025-07-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20250721_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicallanalysis',
            name='action_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_purpose',
            field=models.CharField(max_length=10, verbose_name=[('pi', 'Price Inquiry'), ('wc', 'Warranty Claim')]),
        ),
    ]
