# Generated by Django 3.2.25 on 2025-07-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20250722_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_purpose',
            field=models.CharField(max_length=40, verbose_name=[('pi', 'Price Inquiry'), ('wc', 'Warranty Claim')]),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_status',
            field=models.CharField(max_length=40, verbose_name=[('a', 'Answered'), ('m', 'Missed'), ('v', 'Voicemail'), ('b', 'Busy'), ('f', 'Failed')]),
        ),
    ]
