# Generated by Django 3.2.25 on 2025-07-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20250722_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_purpose',
            field=models.CharField(max_length=40, verbose_name=[('Price Inquiry', 'Priceinquiry'), ('Warranty Claim', 'Warrantyclaim')]),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_status',
            field=models.CharField(max_length=40, verbose_name=[('Answered', 'Answered'), ('Missed', 'Missed'), ('Voicemail', 'Voicemail'), ('Busy', 'Busy'), ('Failed', 'Failed')]),
        ),
    ]
