# Generated by Django 3.2.25 on 2025-07-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20250722_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicallanalysis',
            name='sentiment',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], max_length=10, verbose_name='Sentiment'),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_purpose',
            field=models.CharField(choices=[('Price Inquiry', 'Priceinquiry'), ('Warranty Claim', 'Warrantyclaim')], max_length=40, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_status',
            field=models.CharField(choices=[('Answered', 'Answered'), ('Missed', 'Missed'), ('Voicemail', 'Voicemail'), ('Busy', 'Busy'), ('Failed', 'Failed')], max_length=40, verbose_name='Status'),
        ),
    ]
