# Generated by Django 3.2.25 on 2025-07-22 03:48

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20250722_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_duration',
            field=models.DurationField(default=django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('call_start_time'), '-', django.db.models.expressions.F('call_end_time'))),
        ),
    ]
