# Generated by Django 3.2.25 on 2025-07-22 03:52

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_call_call_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_duration',
            field=models.DurationField(default=django.db.models.expressions.ExpressionWrapper(django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('call_start_time'), '-', django.db.models.expressions.F('call_end_time')), output_field=models.DurationField())),
        ),
    ]
