# Generated by Django 3.2.25 on 2025-07-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_remove_call_call_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='customer_id',
            new_name='agent_id',
        ),
    ]
